version: 2
registries:
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#npm-registry
  npm-github: # Define access for our private NPM registry
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.FINSIT_GITHUB}}
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1000
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "19:00"
      timezone: "Europe/Paris"
    registries: "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "19:00"
      timezone: "Europe/Paris"
